### ISSUE TITLE
[BUG] cardinal_t is the worst name

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#1193] opened 2022-01-22 23:02 UTC
For the second time I expect `cardinal_t<T>` give me `expected_cardinal_t<T>`
I mean that's quite confusing rly.
Let's delete it.

**Comment by jfalcou** [comment] 2022-01-23 09:25
There is an old issue a out that already. We need something that return scalar cardinal for dcalr and correct cardinal or wide anyway.

Remember I alos want to move fixed from type to NTTP so maybe we can have a deep thought on that at this moment.

**Comment by jfalcou** [comment] 2022-01-23 09:26
Duplicate of #886

**Comment by jfalcou** [comment] 2022-01-23 10:45
After mulling over it, here's a proposal:

- [ ] remove scalar_cardinal as it is used mostly nowhere and adapt simd_value accordingly
- [ ] remove cardinal_* and use T::size() everywhere it should have been
- [ ] rename T::size() to T::lanes()
- [ ] rename expected/fundamental_cardinal to something based on lanes

By doing this, it also prepare the change to NTTP lanes in wide type.
What do you think of this ?

**Comment by DenisYaroshevskiy** [comment] 2022-01-23 12:43
I do not mind `size()` or `lanes()`.
This will affect quite some usage links but w/e - we agreed that's what we do.
I don't see why we need scalar cardinal.

**Comment by jfalcou** [comment] 2022-01-23 12:48
It was used at one point, then we discard 99% of its use case when we reworked load/store.
We need to rewrite simd_value and it can be eliminated

**Closed** 2022-01-23 13:05 UTC
Labels: bug
