### ISSUE TITLE
[BUG] Awkward naming.

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#886] opened 2021-08-29 00:18 UTC
I accidentally use `eve::cardinal_v` instead of `eve::expected_cardinal_v`.
Which lead to incorrect code, that would've only been detected in benchmarks.

**Comment by jfalcou** [comment] 2021-11-30 17:17
I forgot to comment on that. I have a PoC where cardinal like fixed are going to turn into NTTP. This will make those meta-functions simpler to implement. The name change will be considered then

**Comment by jfalcou** [comment] 2022-01-23 10:45
Duplicate of #1193

**Closed by jfalcou** 2022-01-23 10:45 UTC
Labels: bug
