### ISSUE TITLE
[PROJECT] improve convert to do two steps

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [jfalcou/eve#534] opened 2021-02-06 11:59 UTC
Converting from let's say uin32 to uint8, for example on  arm, will fall back to scalar.

I think we can in generic case just do convert to next size and then next size.
Needs checking.

**Comment by jfalcou** [comment] 2021-02-06 19:49
This is what we did in the old Boost.SIMD. This works, we just need to add it back.

**Comment by jfalcou** [comment] 2021-02-17 18:03
#348 is a duplicate of to this issue.

**Comment by jfalcou** [comment] 2021-02-28 20:16
Note: this requires native ABI overloads to accept aggregates so we can properly optimizes scenarios like 8 -> 16 bits conversion.

**Comment by jfalcou** [comment] 2022-03-13 15:58
Fixed in 0189e3c

**Closed by jfalcou** 2022-03-13 15:58 UTC
Labels: enhancement, in-progress, **HOT**, [PROJECT]
